/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Gauge: (typeof import('./components/gauge/index.vue'))['default']
    RouterLink: (typeof import('vue-router'))['RouterLink']
    RouterView: (typeof import('vue-router'))['RouterView']
    Seamless: (typeof import('./components/seamless/index.vue'))['default']
    Sinan: (typeof import('./components/sinan/index.vue'))['default']
  }
}
